// resources/web/Layout.vue
<script setup>
import { Link } from '@inertiajs/vue3'
</script>


<template>
    <header>
        <div class="logo">
            <img src="static/logo.svg" alt="" width="86" height="58" />
        </div>
        <nav>
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/contact">Contact</Link>
        </nav>
    </header>
    <main>
        <slot />
    </main>
</template>

// resources/web/Layout.svelte
<script>
    import { inertia } from '@inertiajs/svelte'
</script>

<header>
    <div class="logo">
        <img src="./static/logo.svg" alt="" width="86" height="58" />
    </div>
    <nav>
        <a use:inertia href="/">Home</a>
        <a use:inertia href="/about">About</a>
        <a use:inertia href="/contact">Contact</a>
    </nav>
</header>

<main>
    <slot />
</main>
